Repository gabriel-soulcode/goodpay, pull requests merged in 2023-03, with the labels that each got.

#53 calculadora de regra de 3
  calculadoraRegraTres.html
  css/styleCalculadoraRegraTres.css
  scripts/calculadoraRegraTres.js
Labels: enhancement

#55 Adicionando Toast de Geolocalização
  css/geolocation-style.css
  index.html
  scripts/geolocation-script.js
Labels: documentation, enhancement

#57 Correção do footer
  css/footer.css
  css/style.css
  index.html
Labels: bug

#58 Adição da Calculadora de Porcentagem Simples
  calculadora-porcentagem-simples.html
  css/style-calc-pt.css
  scripts/calculadora-porcentagem-simples.js
Labels: enhancement

#60 Criação calculadora FGTS
  css/fgts.css
  html/fgts.html
  images/logo/iconecalculadora.png
  lib/sweetalert.css
  lib/sweetalert.min.js
  scripts/fgts.js
Labels: documentation, enhancement

#59 criação da faq e comentário no footer.css
  css/footer.css
  css/stylefaq.css
  faq.html
Labels: enhancement

#61 aplicamos um sorteio baseado em promocoes
  promocoes.html
  scripts/promocao.js
Labels: enhancement

#62 Calculadora de Dias
  calculadoraDeDias.html
  css/calculadoraDeDias.css
  scripts/calculadoraDeDias.js
Labels: enhancement

#63 Criação página politicas e privacidade
  css/politicaepivacidade.css
  html/politicaeprividade.html
Labels: documentation, enhancement

#64 Criação dos cards com Grid
  css/grid.css
  index.html
Labels: enhancement

#65 pagina de admnistração
  admPage.html
  css/admPage.css
  scripts/admPage.js
  scripts/main.js
  scripts/usuarios.js
Labels: documentation, enhancement

#66 Criação da calculadora de juros compostos
  calculadoraJurosCompostos.html
  css/styleCalculadoraJurosCompostos.css
  scripts/calculadoraJurosCompostos.js
Labels: documentation, enhancement

#67 Blog financeiro
  blogFinanceiro.html
  css/blogFinanceiro.css
Labels: documentation, enhancement

#68 Criação página parceiros
  css/parceiros.css
  html/parceiros.html
Labels: documentation, enhancement

#69 Criação da página de calendário
  calendar.html
  css/calendar.css
  scripts/calendar.js
Labels: documentation, enhancement

#70 hoje fizemos a criação da tabela icms 2023
  tabela/tabela.css
  tabela/tabelaICMS.html
Labels: documentation, enhancement

#71 criação da página controleFinanceiro e seus adicionais
  controleFinanceiro.html
  css/controleFinanceiro.css
  scripts/controleFinanceiro.js
Labels: documentation, enhancement

#72 Integração das paginas Quizz e seus respectivos arquivos
  css/quizz.css
  quizz.html
  scripts/quizz.js
Labels: documentation, enhancement

#73 Criação da página de login social
  css/socialLogin.css
  images/logo/GoodPayLogin.png
  scripts/loginSocial.js
  social-login.html
Labels: documentation, enhancement

#74 Quem somos
  css/sobreNos.css
  sobreNos.html
Labels: enhancement

#75 Criação da pagina Objetivos Financeiros
  css/objetivosFinanceiros.css
  index.html
  objetivosFinanceiros.html
  scripts/objetivosFinanceiros.js
Labels: enhancement

#78 criação pagina de perfil
  Perfil.html
  css/styleperfil.css
Labels: enhancement

#77 Adição do cadastro com validação
  cadastro-com-validacao.html
  css/pagcadastro.css
  scripts/cadastroComValidacao.js
Labels: enhancement

#87 task de acessibilidade do index.html #25
  css/style.css
  index.html
Labels: enhancement

#89 Criação página dashboard
  css/dashboard.css
  html/dashboard.html
  images/interface/cel.png
  images/interface/celFundo.png
  images/interface/imgGraficos.png
Labels: documentation, enhancement

#90 hoje fizemos uma tela de login que deixa os dados salvos no navegador
  app.html
  app.js
  index.html
  scripts/main.js
Labels: documentation, enhancement

#91 pagina de cadastro colaborador
  cadastroColaborador.html
  css/cadastroColaborador.css
  scripts/cadastroColaborador.js
Labels: documentation, enhancement

#94 Criação da pagina contas bancarias
  contasBancaria.html
  css/ContasBancos.css
  scripts/ContasBancos.js
Labels: enhancement

#95 Criação da página de modais promocionais
  css/modaisPromocao.css
  modaisPromocao.html
Labels: documentation, enhancement

#97 criação da página de recuperação de senha
  css/recuperarSenha.css
  recuperarSenha.html
Labels: documentation, enhancement

#99 criação da página devteam
  css/devteam.css
  html/devteam.html
  images/interface/almir.png
  images/interface/binarBg.jpg
  images/interface/gabriel.png
  images/interface/logo-eletromidia.png
  images/interface/logoSc.png
  images/interface/tnt-energy-drink.png
  scripts/devteam.js
Labels: documentation, enhancement

#100 Adição do modal a página de recuperação de senha
  css/recuperarSenha.css
  recuperarSenha.html
  scripts/scriptRecuperarSenhaModal.js
Labels: documentation, enhancement

#101 (correção) Readicionando o Toast de Offline na App.html
  app.html
Labels: bug

#102 aplicamos cards na pagina de cadastro
  cadastro-com-validacao.html
  css/pagcadastro.css
Labels: documentation, enhancement

#106 Correção do vídeo na página App
  app.html
  css/app.css
Labels: documentation, enhancement

#107 Criação página produtos e serviços
  css/produtoseservicos.css
  html/produtoseservicos.html
Labels: documentation, enhancement

#110 criada a validação do form de recupreção de senha
  recuperarSenha.html
  scripts/scriptRecuperarSenhaModal.js
Labels: bug, documentation, enhancement

#109 Resolvido o problema do Link Quebrado no Blog do SoulCode.html
  soulcode.html
Labels: enhancement

#111 Criação do Modal de incentivo
  app.html
  css/modalIncentivo.css
  index.html
  scripts/modalIncentivo.js
Labels: enhancement

#112 pagina de sorteio
  css/sorteador.css
  scripts/sorteador.js
  sorteador.html
Labels: documentation, enhancement
